website/models.py
from . import db
from flask_login import UserMixin

class Habit(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    habit_name = db.Column(db.String(100))
    category = db.Column(db.String(50))
    type = db.Column(db.String(50))      
    custom_category = db.Column(db.String(100)) 
    start_date = db.Column(db.Date)
    end_date = db.Column(db.Date)
    start_time=db.Column(db.Time)
    end_time=db.Column(db.Time)
    completed=db.Column(db.Boolean, default=False)
    user_id=db.Column(db.Integer,db.ForeignKey('user.id'))
    


class User(db.Model, UserMixin):
    id = db.Column(db.Integer, primary_key=True)
    email = db.Column(db.String(150))
    password = db.Column(db.String(150))
    first_name=db.Column(db.String(150))
    habits = db.relationship('Habit')

website/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
import os
from flask_login import LoginManager



db = SQLAlchemy()
DB_NAME = "database.db"
BASE_DIR = os.path.abspath(os.path.dirname(__file__))
DB_PATH = os.path.join(BASE_DIR, DB_NAME)

def create_app():
    app = Flask(__name__)
    app.config['SECRET_KEY'] = 'CHEIE'
    app.config['SQLALCHEMY_DATABASE_URI'] = f'sqlite:///{DB_PATH}'
    db.init_app(app)
    
    

    from .views import views
    from .auth import auth

    app.register_blueprint(views, url_prefix='/')
    app.register_blueprint(auth, url_prefix='/')
    
    from .models import User, Habit

    
    with app.app_context():
        db.create_all()
           

    login_manager = LoginManager()
    login_manager.login_view = 'auth.login'
    login_manager.init_app(app)

    @login_manager.user_loader
    def load_user(id):
        return User.query.get(id)
    return app

website/auth.py
from flask import Blueprint,redirect, url_for
from flask import render_template, request, flash
from .models import User
from passlib.hash import bcrypt
from . import db
from flask_login import login_user, login_required, logout_user, current_user

auth=Blueprint("auth",__name__)

@auth.route('/login', methods= ['GET', 'POST'])
def login():
    if request.method == 'POST':
        email = request.form.get('email')
        password = request.form.get('password')

        user = User.query.filter_by(email=email).first()
        if user:
            if bcrypt.verify(password, user.password):
                flash('Logged in successfully!', category='success')
                login_user(user, remember=True)
                return render_template("home.html", user=current_user)
            else:
                flash('Incorrect password, try again.', category='error')
        else:
            flash('Email does not exist.', category='error')
            
    return render_template("login.html", user=current_user)

@auth.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('auth.login'))

@auth.route('/sign-up', methods= ['GET', 'POST'])
def signup():
    if request.method == 'POST':
        email = request.form.get('email')
        first_name = request.form.get('firstName')
        password1 = request.form.get('password1')
        password2 = request.form.get('password2')

        user = User.query.filter_by(email=email).first()
        if user:
            flash('Email already exists', category='error')
            return render_template("signup.html", user=current_user)

        if len(email) < 4:
            flash('Email must be greater than 4 characters.', category='error')
        elif len (first_name) <2:
            flash('First name must be greater than 2 characters.', category='error')
        elif password1 != password2:
            flash('Passwords must match.', category='error')
        elif len(password1) < 7:
            flash('Password must be greater than 7 characters.', category='error')
        else:
            new_user = User(email=email, first_name=first_name, password=bcrypt.hash(password1))
            db.session.add(new_user)
            db.session.commit()
            flash('Account created!', category='success')
            login_user(new_user, remember=True)
            return redirect(url_for('views.home'))
    return render_template("signup.html", user=current_user)

website/views.py
from flask import Blueprint, render_template, request, redirect, url_for,flash
from flask_login import login_required, current_user
from .models import Habit
from . import db
from datetime import datetime
from sqlalchemy.exc import SQLAlchemyError

views=Blueprint("views",__name__)

@views.route('/home', methods=['GET','POST'])
@login_required
def home():
    if request.method == 'POST':
        habit_name = request.form.get('habitName')
        category = request.form.get('category')
        type = request.form.get('type')
        custom_category = request.form.get('customCategory', '')
        
        if not habit_name:
            flash('You must enter a habit name', category='error')
            return render_template("home.html", user = current_user)
        if not category:
            flash('You must choose a category', category='error')
            return render_template("home.html", user = current_user)
        if not type:
            flash('You must choose a type', category='error')
            return render_template("home.html", user = current_user)

        if type in ['weekly', 'ocasional']:
            start_datetime_str, end_datetime_str = request.form.get('dateTimeRange').split(' to ')
            start_datetime = datetime.strptime(start_datetime_str, "%Y-%m-%d %H:%M")
            end_datetime = datetime.strptime(end_datetime_str, "%Y-%m-%d %H:%M")
            
            new_habit = Habit(
            habit_name=habit_name,
            category=category,
            type=type,
            custom_category=custom_category,
            start_date=start_datetime.date(),
            end_date=end_datetime.date(),
            start_time=start_datetime.time(),
            end_time=end_datetime.time(),
            user_id=current_user.id
        )
        if type == 'daily':
            start_time_str, end_time_str = request.form.get('time_interval', '').split('-')
            start_time = datetime.strptime(start_time_str, '%H:%M').time()
            end_time = datetime.strptime(end_time_str, '%H:%M').time()
            print(start_time, end_time)
            new_habit = Habit(
            habit_name=habit_name,
            category=category,
            type=type,
            custom_category=custom_category,
            start_date=datetime.now().date(),
            end_date=None,
            start_time=start_time,
            end_time=end_time,
            user_id=current_user.id
        )
            

        
        db.session.add(new_habit)
        try:
            db.session.commit()
        except SQLAlchemyError as e:
            print(e)

        return redirect(url_for('views.calendar'))
        
    return render_template("home.html", user = current_user)

    
@views.route('/calendar')
@login_required
def calendar():

    habits_today = Habit.query.filter_by(user_id=current_user.id, start_date=datetime.now().date()).order_by(Habit.start_time).all()
    return render_template("calendar.html", user=current_user, habits_today=habits_today)


@views.route('/stats')
@login_required
def stats():
    habits_today = Habit.query.filter_by(user_id=current_user.id, start_date=datetime.now().date(), completed=True).all()

    categories = ['work', 'leisure', 'health', 'custom']
    category_counts = {category: 0 for category in categories}

    for habit in habits_today:
        category_counts[habit.category] += 1
    if len(habits_today)>0:
        total_habits = len(habits_today)
    else:
        total_habits=1
    percentages = [round(count / total_habits * 100, 2) for count in category_counts.values()]

    return render_template("stats.html", user=current_user, categories=categories, percentages=percentages)
    
@views.route('/')
def pagina():
    return render_template("home_unauth.html", user = current_user )

@views.route('/submit-completion', methods=['POST'])
@login_required
def submit_completion():
    if request.method == 'POST':
        habit_ids = request.form.getlist('habit_ids')
        for habit_id in habit_ids:
            habit = Habit.query.get(habit_id)
            if habit:
                habit.completed = True
                try:
                    db.session.commit()
                except SQLAlchemyError as e:
                    print(e)

        flash('Completion submitted successfully!', category='success')

    return redirect(url_for('views.calendar'))

website/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %} Habit Tracker {% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css"
        integrity="sha512-iecdLmaskl7CVkqkXNQ/ZH/XLlvWZOJyj7Yy7tcenmpD1ypASozpmT/E0iPtmFIB46ZmdtAc9eNBvH0H/ZpiBw=="
        crossorigin="anonymous" referrerpolicy="no-referrer" />
    <script src="/static/script.js"></script>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL"
        crossorigin="anonymous"></script>

    <style>
        body {
            background-color: #121212;
            color: white;
            min-height: 100vh;
            display: flex;
            flex-direction: column;
        }
    

        .navbar-nav{
            font-size:18px;
            font-weight:bold;
            
        }
        .nav-item{
            margin-left:20px;
        }
        .alert {
            background-color: #2c2c2c;
            color: #fff;
        }
    
        h2 {
            color: white;
        }
    
        .form-control,
        .btn {
            background-color: #212121;
            color: #fff;
        }
    
        .form-select {
            background-color: #212121;
            color: #fff;
        }
    
        .container {
            flex: 1;
        }
    
        .container-socials {
            display: flex;
            justify-content: center;
            align-items: flex-end;
            margin-bottom: 20px;
        }
    
        .container-socials a {
            margin: 0 10px;
        }
    </style>
    {% block style %}
    {% endblock %}

</head>


<body>

    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbar">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbar">
            <div class="navbar-nav">
                {% if user.is_authenticated %}
                <a class="nav-item nav-link" id="home" href="/home"><img src="/static/Habit Flow.png" alt="Logo" height="70" class="d-inline-block align-top"></a>
                <a class="nav-item nav-link" id="calendar" href="/calendar" style="margin-top:20px;">To do Today</a>
                <a class="nav-item nav-link" id="stats" href="/stats" style="margin-top:20px;">My statistics</a>
                <a class="nav-item nav-link" id="logout" href="/logout" style="margin-top:20px;">Log Out</a>
                {% else %}
                <a class="nav-item nav-link" id="home" href="/"><img src="/static/Habit Flow.png" alt="Logo" height="70" class="d-inline-block align-top"></a>
                <a class="nav-item nav-link" id="login" href="/login" style="margin-top:20px;">Log in</a>
                <a class="nav-item nav-link" id="signUp" href="/sign-up" style="margin-top:20px;">Sign up</a>
                {% endif %}
            </div>
        </div>
    </nav>

    {% with messages = get_flashed_messages(with_categories=true) %}

    {% if messages %}
    {% for category, message in messages %}
    {% if category =='error' %}
    <div class="alert alert-danger alert-dismissable fade show d-flex justify-content-between" role="alert">
        {{message}}
        <button type="button" class="btn-close" data-bs-dismiss="alert"></button>
    </div>
    {% else %}
    <div class="alert alert-success alert-dismissable fade show d-flex justify-content-between" role="alert">
        {{message}}
        <button type="button" class="btn-close" data-bs-dismiss="alert"></button>
    </div>
    {% endif %}
    {% endfor %}
    {% endif %}

    {% endwith %}
    <div class="container">
        {% block content %}
        {% endblock %}

    </div>
    <div class="container-socials text-center" id="socials">
        <a href="https://www.facebook.com/" target="_blank" class="btn btn-social-icon btn-facebook"><i
                class="fab fa-facebook-f fa-xl"></i></a>
        <a href="https://www.twitter.com/" target="_blank" class="btn btn-social-icon btn-twitter"><i
                class="fab fa-twitter fa-xl"></i></a>
        <a href="https://www.instagram.com/" target="_blank" class="btn btn-social-icon btn-instagram"><i
                class="fa-brands fa-instagram fa-xl"></i></a>
    </div>

</body>

</html>

website/templates/calendar.html
{% extends "base.html" %}

{% block content %}

<style>
    #socials {
        display: none;
    }
</style>


<div class="mt-5">
    <h2 class="mb-4">Today</h2>
    {% if habits_today %}
    <form method="post" action="{{ url_for('views.submit_completion') }}">
    <ul>
        {% for habit in habits_today %}
        <li>
            {{ habit.habit_name }} : {{ habit.start_time.strftime('%H:%M') }} - {{ habit.end_time.strftime('%H:%M') }}     
            <input class="form-check-input" id="flexCheckDefault" type="checkbox" name="habit_ids" value="{{ habit.id }}" style="margin-left:10px" {% if habit.completed %}checked{% endif %}>
        </li>
        
        {% endfor %}
    </ul>
    <button type="submit" class="btn btn-primary">Submit Completion</button>
    </form>
    {% else %}
    <p>No habits for today.</p>
    {% endif %}
</div>


{% endblock %}

website/templates/home.html
{% extends "base.html" %}

{% block style %}

<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
<script src="https://cdn.jsdelivr.net/npm/flatpickr"></script>
{% endblock %}


{% block content %}


<div class="mt-5">
    <h2 class="mb-4">Habit Tracker</h2>
    <form method="post" action="{{ url_for('views.home') }}">
        <div class="mb-3">
            <label for="habitName" class="form-label">Habit Name</label>
            <input type="text" class="form-control" name="habitName" id="habitName" placeholder="Enter habit name">
        </div>
        <div class="mb-3">
            <label for="category" class="form-label">Category</label>
            <select class="form-select" name="category" id="category">
                <option disabled selected value="">Select...</option>
                <option value="work">Work</option>
                <option value="health">Health</option>
                <option value="leisure">Leisure</option>
                <option value="custom">Custom</option>
            </select>
        </div>

        <div class="mb-3" id="customCategoryInput" style="display:none;">
            <label for="customCategory" class="form-label">Custom Category</label>
            <input type="text" class="form-control" name="customCategory" id="customCategory"
                placeholder="Enter custom category">
        </div>
        <div class="mb-3">
            <label for="type" class="form-label">Type</label>
            <select class="form-select" name="type" id="type">
                <option disabled selected value="">Select...</option>
                <option value="daily">Daily</option>
                <option value="weekly">Weekly</option>
                <option value="ocasional">Ocasional</option>
            </select>
        </div>
        <div class="mb-3" id="intervalInput" style="display:none;">
            <label for= "time_interval" class="form-label">Time interval</label>
            <input type="text" class="form-control" name="time_interval" id="time_interval">
            <small id="intervalHelp" style="color:rgb(66, 68, 68)">eg: 10:35-11:00</small>
        </div>

        <div class="mb-3" id="dateTimeRangeInput" style="display:none;">
            <label for="dateTimeRange" class="form-label">Select Date and Time</label>
            <input type="text" class="form-control" id="dateTimeRange" name="dateTimeRange" data-input>
        </div>

        <button type="submit" class="btn btn-primary" style="margin-top:10px">Add Habit</button>
    </form>
</div>


<script>
    document.getElementById("category").addEventListener("change", function () {
        var customCategoryInput = document.getElementById("customCategoryInput");
        if (this.value === "custom") {
            customCategoryInput.style.display = "block";
        } else {
            customCategoryInput.style.display = "none";
        }
    });

    document.getElementById("type").addEventListener("change", function () {
            var intervalInput = document.getElementById("intervalInput");
            if (this.value === "daily") {
                intervalInput.style.display = "block";
            } else {
                intervalInput.style.display = "none";
            }
        });

       document.getElementById("type").addEventListener("change", function () {
            var dateTimeRangeInput = document.getElementById("dateTimeRangeInput");

            if (this.value === "weekly" || this.value === "ocasional") {
                dateTimeRangeInput.style.display = "block";
                flatpickr("#dateTimeRange", {
                    enableTime: true,
                    time_24hr: true,
                    dateFormat: "Y-m-d H:i",
                    enableSeconds: false,
                    mode: "range",
                });
            } else {
                dateTimeRangeInput.style.display = "none";
            }
        });

</script>

{% endblock %}

website/templates/home_unauth.html
{% extends "base.html" %}

{% block content %}
<div id="intro-text" class="container text-center">
    <div  class="container text-center">
        <img src="/static/Habit Flow.png" alt="Logo" height="200" class="d-inline-block align-top" >
    </div>
<h3 style="margin-top:20px; margin-bottom:40px;">Change your habits and improve your life today!</h3>

<a href="/sign-up" class="btn btn-primary" style="margin-top: 10px">Get Started</a>
</div>

{% endblock %}

website/templates/login.html
{% extends "base.html" %}
{% block title %} Log In {% endblock %}

{% block content %} 


<form method="POST">
    <h3 align="center">Log in</h3>
    <div class="form-group">
        <label for="email">Email Adress</label>
        <input type="text" class="form-control" id="email" name="email" placeholder="Enter email" />
    </div>

    <div class="form-group">
        <label for="password">Password</label>
        <input type="password" class="form-control" id="password" name="password" placeholder="Enter password" />
    </div>
<a href="/sign-up" style="color:rgb(66, 68, 68)">Don't have an account? Sign up!</a>

    <br />
    <button type="submit" class="btn btn-primary">Log In</button>
</form>

{% endblock %}

website/templates/signup.html
{% extends "base.html" %}
{% block title %} Sign Up {% endblock %}

{% block content %} 
<form method="POST">
<h3 align="center">Sign up</h3>
<div class="form-group">
    <label for="email">Email Adress</label>
    <input type="text" class="form-control" id="email" name="email" placeholder="Enter email"/>
</div>

<div class="form-group">
    <label for="firstName">Name</label>
    <input type="text" class="form-control" id="firstName" name="firstName" placeholder="Enter first name" />
</div>

<div class="form-group">
    <label for="password1">Password</label>
    <input type="password" class="form-control" id="password1" name="password1" placeholder="Enter password" />
</div>

<div class="form-group">
    <label for="password2">Confirm Password</label>
    <input type="password" class="form-control" id="password2" name="password2" placeholder="Confirm password" />
</div>
<a href="/login" style="color:rgb(66, 68, 68)">Already have an account? Log in!</a>
<br/>
<button type="submit" class="btn btn-primary">Submit</button>
</form>

{% endblock %}

website/templates/stats.html
{% extends "base.html" %}

{% block content %}
<div class="mt-5">
    <h2 class="mb-4" style="text-align:center">Statistics</h2>
    <div style="max-width:500px; margin:auto;">
        <canvas id="categoryChart" width="500" height="500"></canvas>
    </div>
</div>

<style>
    #socials{
        display:none;
    }
</style>

<script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
<script>
    document.addEventListener('DOMContentLoaded', function () {
        var ctx = document.getElementById('categoryChart').getContext('2d');

        var data = {
            labels: {{ categories| tojson | safe
    }},
        datasets: [{
            data: {{ percentages| tojson | safe }},
        backgroundColor: [
            'rgba(255, 99, 132, 0.8)',
            'rgba(54, 162, 235, 0.8)',
            'rgba(255, 200, 100, 1)',
            'rgba(2, 150, 50, 1)'
        ],
            }],
        };

    var options = {
        responsive: true,
        maintainAspectRatio: false,
    };

    var categoryChart = new Chart(ctx, {
        type: 'pie',
        data: data,
        options: options,
    });
    });
</script>
{% endblock %}